### PR TITLE
Added abillity to return interval id to clear it if needed.

### PR DESCRIPTION
**Pull request by gate8team**
Hey, Daynin. I've added some mini fix to your lib, so now we can retrieve timer interval ids. I've made it just to have ability to stop animation anytime I like. Here is the simple example to demonstrate how we could call it:

```javascript
...
// let's clear interval after 3 wodry executions
var intervalId = $element.wodry({
                    delay: 2500,
                    styles: Array.apply(null, Array(flipParts.length)).map(function () { return classes }),
                    animation: 'rotateX',
                    callback: function() {
                        if (++i == 2 && intervalId != null && intervalId[0] != null) {
                            clearInterval(intervalId[0]);
                        }
                    }
                  });
...
```

### CODE REVIEW

**Comment by daynin** [comment]
@gate8team, can you write some documentation for this feature in README.md?

**Comment by gate8team** [comment]
Yeah, sure

**Comment by daynin** [comment]
@gate8team 
Thank you for your contribution!

**Comment by gate8team** [comment]
No problem, thank you for your pretty lib! :)

**Pull request merged**
